langage: android
jdk: openjdk8

env:
  global:
    -ANDROID_API_LEVEL=19
    -ANDROID_BUILD_TOOLS_VERSION=28.0.0

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-$ANDROID_API_LEVEL

licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

script:
  - ./gradlew build check --stacktrace